import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
	title: "Mariella",
	description: "Generated by create next app",
};

interface RootLayoutProps {
	children: ReactNode;
}

export default function RootLayout(props: RootLayoutProps) {
	return (
		<html lang="en">
			<body>{props.children}</body>
		</html>
	);
}
